### ISSUE TITLE
Convert Site HTML Code to Python Flask Framework

### ISSUE THREAD

**Issue by zehro** [zehro/UAH-Theatre#7]
## Description
On the recommendation of Katerin, we will be using Python Flask and moving all of our HTML code into a Heroku Server using the Python Flask framework.

## Tasks
- [x] Migrate HTML code over to Heroku server
- [x] Integrate Python Flask into server

## Done Done Criteria
1. Test the application after migrating to the new server
2. Test some basic REST API via Python Flask

**Comment by ghost** [comment]
We decided to do local development with localhost instead of pushing codes to the remote server right at the beginning.
Issue: Currently the routing is done entirely within the static html files using "a href=..." The UI needs to be converted into a frontend app with appropriate routing. Is this done already using some sort of framework on your dev version? @zehro

**Comment by zehro** [comment]
It currently is not, but it will be as soon as I review more of the Flask framework. It will be pushed out as soon as possible.
